### ISSUE TITLE
Constantly rebooting when running on qemu

### ISSUE THREAD

**Issue by TKX42** [mrgian/felix#3]
It is constantly rebooting after this point when i tried to run the built image on qemu.
![image](https://user-images.githubusercontent.com/49553574/230888686-74e73301-d674-4bc6-bf74-f08408b0c455.png)
When running with `-no-reboot` qemu just quickly closes:
```
PS C:\Users\trist\Downloads\felix-main\felix-main> qemu-system-i386 -drive file=build/disk.img,index=0,media=disk,format=raw,if=ide -no-reboot

(qemu:14460): Gtk-WARNING **: 12:55:30.708: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
PS C:\Users\trist\Downloads\felix-main\felix-main>

```

**Comment by TKX42** [comment]
Looks like it is the same error as this: https://stackoverflow.com/questions/57373848/qemu-triple-faulting-when-enabling-interrupts

**Comment by mrgian** [comment]
It's due a unexpected behavior caused by static mutables.
For some reason the interrupt descriptor table gets overwritten random data, so when an interrupt cpu does not jump to the expected handler.
I'm working on a fix.

By the way, have you built the image using build.sh script or using docker?

**Comment by TKX42** [comment]
Ok, so I tried a lot of things:
- Building via docker: Doesn't run with qemu on neither windows nor WSL
- Building directly on WSL: Doesn't run either
- Running an image from the releases: Works on both windows and WSL
- Building on a Kali Linux VM: Runs via qemu on Kali Linux

Looks like it is something Windows specific when building however i don't understand why it then won't run when built on WSL or docker. My WSL is running ubuntu.

**Comment by mrgian** [comment]
Maybe different versions of the tools used in build script lead to different behaviors.
However it should be fixed now.

Can you try building again in those different environments and check if it works now? 
It would be very helpful.

**Comment by TKX42** [comment]
yes, works both when built directly with the script on WSL and with docker on windows

**Comment by mrgian** [comment]
Thank you for testing!
