### ISSUE TITLE
Use raw pointers instead of asm for writing bytes

### ISSUE THREAD

**Issue by wtholliday** [mrgian/felix#5]
https://github.com/mrgian/felix/blob/bc0b1023027404262ef7b82ba454cc3b772eba47/kernel/src/print.rs#L51

Looks like it's just writing a byte to memory, but I don't know asm very well.

Just wondering :)

**Comment by mrgian** [comment]
Actually no, it's not needed. 
I was just too used to asm, and I didn't think I could use pointers.
Something like this would be the same `let p = pointer as *mut u8; *p = c as u8;`

I'm renaming the issue. I will close it when I have replaced all the unnecessary asm macros.

Thank you for letting me notice!

**Comment by mrgian** [comment]
Solved with [https://github.com/mrgian/felix/commit/fe1da95b579848b995f95d0d8b95738b3fdec9e1]()
